const LIVE_USAGE_DIAGNOSTIC_CODE = 'amxx.live.usage';
const LIVE_DYNAMIC_USAGE_DIAGNOSTIC_CODE = 'amxx.live.dynamicUsage';
const LIVE_UNRESOLVED_INCLUDE_DIAGNOSTIC_CODE = 'amxx.live.unresolvedInclude';

const EDITED_GLOBAL_REPLACEMENT_DIAGNOSTIC_CODES = Object.freeze([
    LIVE_USAGE_DIAGNOSTIC_CODE,
    LIVE_DYNAMIC_USAGE_DIAGNOSTIC_CODE
]);

module.exports = {
    LIVE_USAGE_DIAGNOSTIC_CODE,
    LIVE_DYNAMIC_USAGE_DIAGNOSTIC_CODE,
    LIVE_UNRESOLVED_INCLUDE_DIAGNOSTIC_CODE,
    EDITED_GLOBAL_REPLACEMENT_DIAGNOSTIC_CODES
};
